### ISSUE TITLE
无法启用插件的BUG报告，对上传文件功能的一些疑问，以及静态文件cdn的建议

### ISSUE THREAD

**Issue by balthild** [yb/qiniu-file-for-typecho#1]
1.在Github上直接下载下来的版本（master）上传到网站上，点下启用插件就显示500 错误，typecho1.0，目前我使用的是这个版本就没有问题：http://pan.baidu.com/s/1hq43dys
2.目前网站和插件已经正确配置，我想问一下这个插件在上传图片后是直接上传到七牛，还是仍然上传到本地空间，在第一次访问时才拉取到七牛？需不需要在七牛空间那边设置镜像加速？
3.希望增加对本地css/js等等静态文件的cdn加速功能（我觉得这个直接使用文件地址替换即可）

**Comment by abelyao** [comment]
1. 500错误的原因有许多，目前没有更详细的异常来判断问题所在，没法帮到你，如果你发现了 bug 的具体位置甚至解决的方法，非常欢迎你提交 issue 我会马上跟进。
2. 每次通过附件上传图片的时候先传到你的空间临时目录，然后由 PHP 转存到七牛那边，由于主机这边是存在临时目录，所以并不占用空间，会自动删除的。不需要启用镜像加速，如果要启用镜像加速，则不需要使用插件了，七牛会帮你在第一次访问的时候自动拉取。
3. 这个插件一开始是自己使用，当时自己的博客几个静态文件加起来也没 5K 加上有 gzip 输出所以实际效果比放到 cdn 还更好一些（貌似 cdn 是没有 gzip 输出的）。后续如果有更新的话，会考虑把这个也加上，不过目前来看… 估计是个坑了…

谢谢反馈~ 谢谢使用~

**Comment by balthild** [comment]
对于这个500错误，typecho也没有输出任何其他的错误信息……我是刚刚开始用typecho这个程序，所以不怎么能了解它……

**Comment by balthild** [comment]
噢不好意思，刚刚百度了一下，才找到输出错误信息的话方法。

```
无法启用插件

exception 'Typecho_Widget_Exception' with message '无法启用插件' in F:\xampp\htdocs\typecho\var\Widget\Plugins\Edit.php:93
Stack trace:
#0 F:\xampp\htdocs\typecho\var\Widget\Plugins\Edit.php(292): Widget_Plugins_Edit->activate('qiniu-file-for-...')
#1 F:\xampp\htdocs\typecho\var\Widget\Do.php(81): Widget_Plugins_Edit->action()
#2 F:\xampp\htdocs\typecho\var\Typecho\Widget.php(222): Widget_Do->execute()
#3 F:\xampp\htdocs\typecho\var\Typecho\Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#4 F:\xampp\htdocs\typecho\index.php(23): Typecho_Router::dispatch()
#5 {main}
```

**Comment by ghosthim** [comment]
我也遇到了这个问题，请问您是怎么解决的？

**Comment by balthild** [comment]
@ghosthim 从github直接下下来的就有问题，在作者博客提供的百度云下载的就没有问题

**Comment by ghosthim** [comment]
@s-kias   OK.谢谢了~~
